"""
api/app.py
----------
FastAPI application for the TransitLens ML Core API.

Startup:
    uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload

Endpoints:
    GET  /health           — service health check
    POST /analyze          — analyse a light curve (full pipeline)
    GET  /demo/{candidate} — run a synthetic demo case
    GET  /docs             — Swagger UI (auto-generated by FastAPI)

CORS is configured to allow all origins for hackathon flexibility.

Used by: uvicorn, transitlens-platform
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api.middleware import TimingMiddleware
from api.routes import router

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("api")


# ---------------------------------------------------------------------------
# Application factory
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(application: FastAPI):
    """Startup and shutdown events."""
    logger.info(
        "TransitLens ML Core API started — "
        "visit http://localhost:8000/docs for Swagger UI"
    )
    yield


app = FastAPI(
    title="TransitLens ML Core API",
    description=(
        "AI-enabled detection and classification of exoplanet transit signals "
        "from noisy astronomical light curves. Provides BLS period detection, "
        "11-feature extraction, rule-based classification, calibrated confidence "
        "scoring, and four diagnostic plots."
    ),
    version="0.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Middleware (order: outermost first)
# ---------------------------------------------------------------------------

# CORS — allow all origins for hackathon demo
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request timing and logging
app.add_middleware(TimingMiddleware)


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

app.include_router(router)



